### ISSUE TITLE
SwiftLintPlugin Error

### ISSUE THREAD

**Issue by kean** [will-lumley/FaviconFinder#100]
Hey, you get the following error after adding the package to a project. It would be awesome to exclude the plugins from the package if possible so that the consumers wouldn't have to depend on the development dependencies.

<img width="364" alt="Screenshot 2024-10-14 at 9 38 12 AM" src="https://github.com/user-attachments/assets/a25420a6-91ab-43b8-a3cd-f7dad90e0c5b">

**Comment by will-lumley** [comment]
Hey @kean - thanks for flagging this. I'll disable the plugin for you now.

**Comment by will-lumley** [comment]
This should be resolved now in `5.1.3`. If the issue continues to persist, please let me know and I'll get onto it. 
Thanks once more for raising this as an issue.

**Comment by kean** [comment]
Thank you! 🙇  
I hope SwiftPM adds support for dev dependencies In the future, but I won't hold my breath on it.
