### ISSUE TITLE
FaviconFinder no longer retrieves favicon when header image is present

### ISSUE THREAD

**Issue by mergesort** [will-lumley/FaviconFinder#103]
I've been using this code to fetch favicons, and it's been relatively unchanged. Since upgrading to 5.1.3 (from a previous 5.x version, I don't remember which one specifically because I was working off my own branch with other fixes), instead of returning favicons the library is now returning header images, when they are present on a website.

You can see it here, in the top left icon where I display favicons, it's now displaying the header image that my websites have. That means when a user saves a link, they now see the header image presented twice, rather a favicon and the header image.

<img src="https://github.com/user-attachments/assets/33fe911b-e7e8-46a6-8cdb-671579043ba3" width="461" height="1000" />

This is the code I'm using to retrieve the Favicon, with seemingly no major changes since upgrading.
```swift
struct FaviconParser {
    static func fetchFaviconURL(from url: URL) async throws -> ImageMetadata? {
        let faviconFinder = FaviconFinder(url: url)
        let favicons = try? await faviconFinder.fetchFaviconURLs()

        guard let favicon = try? await favicons?.largest() else { return nil }

        return ImageMetadata(
            url: favicon.source,
            width: nil,
            height: nil
        )
    }
}
```

If this is new functionality that has been added, can there be an explicit way to exclude header images from being parsed? (Or better yet, specify that you wish to include header images when scraping a webpage for favicons.)

Thank you very much as always @will-lumley!

**Comment by will-lumley** [comment]
@mergesort Thanks for raising this. There is now a parameter named `acceptHeaderImage` of `Bool` type in the `FaviconFinder.Configuration`. This value is `false` by default, making the functionality opt-in.

Another user had raised this as an issue as they wanted the library to download these image types. I had a knee-jerk reaction which led to me implementing it immediately without thinking of the consequences. I see now that I should have thought about the wider reaching effects of this - and will think about these sorts of things going forward.

Thanks again for reaching out and taking the time to raise this issue, and for your patience.

**Comment by mergesort** [comment]
Thank you very much for this fix! I can definitely understand how you got there, it does seem like a helpful feature. But I do appreciate the reversion and keeping the default as it was before. 🙇🏻‍♂️
