### ISSUE TITLE
Create a method that only returns the URL

### ISSUE THREAD

**Issue by lfarah** [will-lumley/FaviconFinder#16]
Hey @will-lumley, loved FavIconFinder! I'm currently using for [my personal project](https://github.com/lfarah/Update) so I can get a RSS feed's image if I can't get it from the RSS feed object.

I'm currently using [SDWebImageSwiftUI](https://github.com/SDWebImage/SDWebImageSwiftUI) to show the images, so it would be great to have only the image URL so SDWImage can handle downloading cashing these images

**Comment by will-lumley** [comment]
Hey @lfarah - thanks for the compliment and feedback! 😊

I've merged your pull request and released a new version (2.1.1) which has this feature implemented.
