### ISSUE TITLE
init(data:) is unavailable in Mac Catalyst

### ISSUE THREAD

**Issue by lfarah** [will-lumley/FaviconFinder#18]
I'm getting an error when trying to use FaviconFinder for the Mac:

<img width="881" alt="Screen Shot 2020-02-11 at 2 51 58 PM" src="https://user-images.githubusercontent.com/6511079/74263778-3abae900-4cde-11ea-869e-9fbb5b471f40.png">

**Comment by will-lumley** [comment]
@lfarah Are you still experiencing this in the latest version?

**Comment by lfarah** [comment]
No. My PR fixed this. Thanks
