### ISSUE TITLE
Does Not Support SwiftUI

### ISSUE THREAD

**Issue by Jerland2** [will-lumley/FaviconFinder#26]
By using the following type aliases you cannot use this with SwiftUI easily since the UI Image Component in SwiftUI is `Image`

Code that causes the issue:
```
#if targetEnvironment(macCatalyst)
import UIKit
public typealias Image = UIImage

#elseif canImport(AppKit)
import AppKit
public typealias Image = NSImage

#elseif canImport(UIKit)
import UIKit
public typealias Image = UIImage

#endif
```

Need to rename the typelias to something other than `Image`

**Comment by will-lumley** [comment]
@Jerland2 This should now be resolved. Let me know if you have any further issues with this issue.
