### ISSUE TITLE
Follow meta refresh redirects

### ISSUE THREAD

**Issue by alexstaravoitau** [will-lumley/FaviconFinder#49]
I know this is a very specific use case, but some websites use something called *meta refresh redirects*, i.e. a client-side redirect which the browser interprets itself, using HTML's head tag for destination URL. This is unlike 301 and 302 redirects that happen on the web server.

This is what `URLSession`'s data task returns in this case (currently working with URL https://www.sympy.org/):

```html
<html>
<head>
   <meta http-equiv="refresh" content="0;URL=en/index.html">
</head>
</html>
```

Essentially, when the browser finishes loading these contents of https://www.sympy.org/, it immediately redirects to https://www.sympy.org/en/index.html. It would be great if `FaviconFinder` knew how to follow those client-side redirects, and resolved the final destination HTML, instead of the intermediary one above — which doesn't have a favicon.

**Comment by will-lumley** [comment]
Hey @navoshta - thanks for raising this!
What an interesting use case, thank you for taking the time to explain it. This is something that I'd absolutely be interested in looking at, and will be doing so over the next week or so.

**Comment by will-lumley** [comment]
@navoshta The issue is now closed as the feature has been implemented. Let me know how it goes for you!
It's in version 3.3.0.

**Comment by alexstaravoitau** [comment]
@will-lumley Seems to work well — thank you for addressing this so quickly! 🚀
