### ISSUE TITLE
Querying "https://www.qq.com" failed.

### ISSUE THREAD

**Issue by yangliu-1995** [will-lumley/FaviconFinder#58]
Because  the encoding name in response of "https://www.qq.com" is `gb2312` not utf8, so the html string is nil.

**Comment by yangliu-1995** [comment]
```
let (data, response) = try await URLSession.shared.data(for: request)
guard let httpResponse = response as? HTTPURLResponse else {
          return
      }
var encoding = String.Encoding.utf8
if let encodeName = httpResponse.textEncodingName {
    let cfe = CFStringConvertIANACharSetNameToEncoding(encodeName as CFString)
    let se = CFStringConvertEncodingToNSStringEncoding(cfe)
    encoding = String.Encoding(rawValue: se)
}
if let string = String(data: data, encoding: encoding) {
    // Do something
}
```
I think it would be better to get the html string by the above code instead of fixing the data using utf-8 as the encoding.

**Comment by will-lumley** [comment]
@yangliu-1995 Good catch! I'll write up a PR for this later this week and resolve it.

**Comment by yangliu-1995** [comment]
Thanks!
Have you considered providing a method that returns only the icon url? Because I want to download images via SDWebImage or Kingfisher so that I can easily use their cache.

**Comment by will-lumley** [comment]
@yangliu-1995 Let me know if I misunderstand your question - but as far as I know FaviconFinder currently already does that. It returns a struct named `Favicon` which contains the image, url, data, etc. You can find it here: https://github.com/will-lumley/FaviconFinder/blob/main/Sources/FaviconFinder/Classes/Types/Favicon.swift

**Comment by yangliu-1995** [comment]
Sorry, my English is not very good, I meant to get only the URL of the icon without downloading it, the task to download it I want to use sdwebimage.

**Comment by will-lumley** [comment]
@yangliu-1995 I understand now ☺️ That's a great feature request - I'll implement that after this bug fix. You can expect these two to be done later tonight.

**Comment by will-lumley** [comment]
@yangliu-1995 This has been fixed and is in version 4.0.1 😀
Let me know if you have any issues with it!

**Comment by yangliu-1995** [comment]
Thank you so much, this has helped me so much.

**Comment by will-lumley** [comment]
@yangliu-1995 I have also implemented functionality that allows you to fetch favicon URL without downloading image. 🎉
Just need to set `downloadImage` to false in FaviconFinder initiator. I have updated README if you want an example.

**Comment by yangliu-1995** [comment]
Thank you very much, sorry for the late reply, I was too busy at work these two days.
