### ISSUE TITLE
Feature Request: Linux Support

### ISSUE THREAD

**Issue by mergesort** [will-lumley/FaviconFinder#63]
Hi @will-lumley, I'm in the middle of migrating a lot of functionality I had running on the client to Vapor, which includes fetching favicons. Unfortunately the one library I'm having trouble getting up and running is FaviconFinder. 

I actually started to add the necessary changes for example adding conditional imports like this, as needed. (See: attached project)
```swift
#if targetEnvironment(macCatalyst)
import UIKit
public typealias FaviconImage = UIImage

#elseif canImport(AppKit)
import AppKit
public typealias FaviconImage = NSImage

#elseif canImport(UIKit)
import UIKit
public typealias FaviconImage = UIImage

#elseif os(Linux)
import Foundation
import FoundationNetworking
public struct FaviconImage {
    public var data: Data = .init()
}
#endif
```

It doesn't seem like it should be too tricky to add Linux support, but I'm getting a little tripped up on URLSession-related errors. This is a sample of the errors, they all seem to be around URLSession having a different API on Linux than on Apple platforms. 
```swift
/package/Sources/FaviconFinder/Classes/Finders/WebApplicationManifestFaviconFinder.swift:184:52: error: value of type 'URLSession' has no member 'data'
        let response = try await URLSession.shared.data(from: manifestURL)
                                 ~~~~~~~~~~~~~~~~~ ^~~~
/package/Sources/FaviconFinder/Classes/Toolbox/FaviconURLRequest.swift:21:55: error: value of type 'URLSession' has no member 'data'
        let urlResponse = try await URLSession.shared.data(from: url)
                                    ~~~~~~~~~~~~~~~~~ ^~~~
/package/Sources/FaviconFinder/Classes/Toolbox/FaviconURLRequest.swift:62:52: error: value of type 'URLSession' has no member 'data'
                return try await URLSession.shared.data(from: redirectURL)
                                 ~~~~~~~~~~~~~~~~~ ^~~~
/package/Sources/FaviconFinder/Classes/Toolbox/FaviconURLRequest.swift:80:52: error: value of type 'URLSession' has no member 'data'
                return try await URLSession.shared.data(from: redirectURL)
                                 ~~~~~~~~~~~~~~~~~ ^~~~
[68/78] Compiling FaviconFinder FaviconURLRequest.swift
/package/Sources/FaviconFinder/Classes/Finders/WebApplicationManifestFaviconFinder.swift:184:52: error: value of type 'URLSession' has no member 'data'
        let response = try await URLSession.shared.data(from: manifestURL)
                                 ~~~~~~~~~~~~~~~~~ ^~~~
/package/Sources/FaviconFinder/Classes/Toolbox/FaviconURLRequest.swift:21:55: error: value of type 'URLSession' has no member 'data'
        let urlResponse = try await URLSession.shared.data(from: url)
                                    ~~~~~~~~~~~~~~~~~ ^~~~
/package/Sources/FaviconFinder/Classes/Toolbox/FaviconURLRequest.swift:62:52: error: value of type 'URLSession' has no member 'data'
                return try await URLSession.shared.data(from: redirectURL)
                                 ~~~~~~~~~~~~~~~~~ ^~~~
/package/Sources/FaviconFinder/Classes/Toolbox/FaviconURLRequest.swift:80:52: error: value of type 'URLSession' has no member 'data'
                return try await URLSession.shared.data(from: redirectURL)
                                 ~~~~~~~~~~~~~~~~~ ^~~~
```

You can see this for yourself if you open the project, run `docker build --tag favicon . `, and then `docker run favicon` to see the output.

I figured you may have some more expertise in the domain given your great work on the library, and was wondering if you could either help me figure out how to work around these errors, or perhaps integrate Linux directly into your version of FaviconFinder?

And I just want to say thank you so much for the library, it's served me really well, and I'd love to keep using it as my project evolves. 🙂

**Comment by will-lumley** [comment]
Hi @mergesort, thanks for reaching out. Very happy to hear you've been enjoying this framework (outside of the mentioned Linux issue). Thank you for providing the compiler errors.
I'll look into this issue shortly and aim to integrate Linux support directly into my version of FaviconFinder by the end of the week.

**Comment by mergesort** [comment]
Thanks a lot @will-lumley! I look forward to using FaviconFinder on the server, and appreciate you looking into it!

**Comment by mergesort** [comment]
Whoops, just realized I never uploaded the project I was working with!
[FaviconFinder.zip](https://github.com/will-lumley/FaviconFinder/files/10739112/FaviconFinder.zip)

**Comment by will-lumley** [comment]
@mergesort At the heart of the issue was that Swift on Linux doesn't yet support async/await concurrency. So I've re-implemented parts of it with closures where necessary. This closure-based API is available to Linux only, iOS/macOS devs will still have access to the async/await style concurrency.

Can you let me know if this works for you? See attached PR.

**Comment by mergesort** [comment]
Hey @will-lumley, this looks pretty good!

You noted that Linux doesn't support async/await, but I can confirm that it does (since a lot of my backend is using it. 🙂) You're close though, it looks like the async/await `URLSession` APIs were never ported to Linux for whatever reason, possibly because Apple is using NIO for their networking layer.

With that in mind I think we can get to a point where you could expose a single `downloadFavicon()` function, rather than adding the separate `func downloadImage(at url: URL, type: FaviconType, onDownload: @escaping OnDownloadComplete)` specifically for Linux. To do this we would need to wrap the Linux variant using `withCheckedContinuation`. The benefit of this is that no matter what platform you're on, the caller of `downloadFavicon()` won't have to add their own `#if os(Linux)` checks, which would be really nice.

I'm actually 3 hours from going on a 10 day vacation so I was only able to take one shot at deploying to Linux, but didn't get it deployed because in my rush I missed your note about Linux only supporting the completion-handler version. I don't expect to be deploying any code but I may pop in, try out any changes, and leave a comment or two when I have some free time. 

Sorry for the timing, _but_ when I was checking to see if `withCheckedContinuation` was available on Linux I stumbled upon a [blog post](https://diegolavalle.com/posts/2021-11-11-urlsession-concurrency-linux/) that discusses this scenario, and I think that should at the very least make what I'm suggesting pretty clear.

Hope that's useful feedback, and I very much appreciate you helping me with my problem Will. 🙇🏻‍♂️

**Comment by mergesort** [comment]
Hey @will-lumley, I just wanted to check and see if you were planning on implementing the suggestion of adding async/await or not? If not I'll just build my own shim over the great work you've done here to add Linux support, but it'd be really nice to leverage async/await out the box.

Thanks a lot!

**Comment by will-lumley** [comment]
Hey @mergesort - really sorry for going AWOL. Got married very recently and that took over my time and I forgot to let you know here. I'll be back tomorrow and will resolve it then :)

**Comment by mergesort** [comment]
Will, that's as good a reason as any that I can think of, I hope you two had a great wedding and are very happy! I just wanted to know if I should add support so take your time —  I'll start using it whenever it's ready. And of course, congratulations! 🙂

**Comment by mergesort** [comment]
Hey @will-lumley, I hate to impose because I know open source is a labor of love, but I was wondering if you'd made any progress on this. I intend to get back to the project I'm using this for next week and figured I'd check. If not I can take over the patch in a week or two, but figured I'd check and see if you had any plans on finishing this portion of the PR.
