### ISSUE TITLE
Can not import FaviconFinder.

### ISSUE THREAD

**Issue by FledgeXu** [will-lumley/FaviconFinder#83]
Hi,
  Thanks for your work, but when I tried to import FaviconFinder and I hit an issue which Xcode keep throwing errors and here is the error message:

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/10226dab-513f-4199-9253-3c2f028d6084">

Maybe it relates to `swiftlint`? Thanks for your help.

**Comment by will-lumley** [comment]
Thanks @FledgeXu - I'll look into this ASAP.

**Comment by will-lumley** [comment]
@FledgeXu Are you using the latest version? Or are you specifying from `main`?

**Comment by FledgeXu** [comment]
I was use the last release, the 5.0.3.
And here are my other dependencies:
<img width="905" alt="image" src="https://github.com/user-attachments/assets/872f617b-bc99-4b08-9ffd-c84864b1de64">

**Comment by will-lumley** [comment]
Thanks for the info - that's very helpful. Can you try 5.0.4 (release just a minute ago) for me and tell me how that goes?

**Comment by FledgeXu** [comment]
Thanks a lot, It has been fixed!

**Comment by will-lumley** [comment]
Awesome to hear it! Thank you for bearing with me as I worked through it, really appreciate that.
Have a lovely weekend!
