### ISSUE TITLE
Any plan to support Swift6?

### ISSUE THREAD

**Issue by FledgeXu** [will-lumley/FaviconFinder#86]

**Comment by will-lumley** [comment]
Swift 6 is now supported. The version `5.1.0` will be the Swift 6 implementation - and will be released in a few hours.
Let me know if you need any assistance :)

**Comment by mergesort** [comment]
@will-lumley Would you mind supporting both Swift 5 and Swift 6 at the same time, by vendoring multiple Package.swift flies [like this](https://forums.swift.org/t/is-it-possible-to-support-swift-5-and-6-in-one-package/72429/2)?

My project is not yet compatible with Swift 6, so the dependency cannot be resolved on systems still using Swift 5.

>Computing version for https://github.com/will-lumley/FaviconFinder
>error: Dependencies could not be resolved because 'faviconfinder' >= 5.1.0 contains incompatible tools version (6.0.0) and root depends on 'faviconfinder' 5.1.1..<6.0.0.

**Comment by mergesort** [comment]
I went ahead and [made a change on a branch](https://github.com/will-lumley/FaviconFinder/compare/main...mergesort:FaviconFinder:main) which should work, if you need an example or want me to create a pull request.

**Comment by will-lumley** [comment]
@mergesort Amazing, thank you for this. I'll create the PR now and push this through once CI has passed.
